### Generated by Winemaker 0.8.4
###
### Invocation command line was
### /usr/bin/winemaker --lower-uppercase -DSTRICT .


SRCDIR                = .
SUBDIRS               =
DLLS                  =
LIBS                  =
EXES                  = d2gs



### Common settings

CEXTRA                =
CXXEXTRA              =
RCEXTRA               =
DEFINES               = -DSTRICT
INCLUDE_PATH          = -I.
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### d2gs sources and settings

d2gs_MODULE           = d2gs
d2gs_C_SRCS           = bnethash.c \
			callback.c \
			charlist.c \
			config.c \
			d2gamelist.c \
			d2ge.c \
			debug.c \
			eventlog.c \
			handle_s2s.c \
			hexdump.c \
			main.c \
			net.c \
			telnetd.c \
			timer.c \
			utils.c \
			vars.c \
			versioncheck.c
d2gs_CXX_SRCS         =
d2gs_RC_SRCS          = res/d2server.rc
d2gs_LDFLAGS          = -mwindows
d2gs_ARFLAGS          =
d2gs_DLL_PATH         =
d2gs_DLLS             = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
d2gs_LIBRARY_PATH     =
d2gs_LIBRARIES        = uuid \
			ws2_32


d2gs_OBJS             = $(d2gs_C_SRCS:.c=.o) \
			$(d2gs_CXX_SRCS:.cpp=.o)
#			$(d2gs_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(d2gs_C_SRCS)
CXX_SRCS              = $(d2gs_CXX_SRCS)
RC_SRCS               = $(d2gs_RC_SRCS)


### Tools

CC = gcc
CXX = g++
RC = windres
AR = gcc-ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .c .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(d2gs_MODULE): $(d2gs_OBJS)
	$(CC) $(d2gs_LDFLAGS) -o $@ $(d2gs_OBJS) $(d2gs_LIBRARY_PATH) $(d2gs_DLL_PATH) $(DEFLIB) $(d2gs_DLLS:%=-l%) $(d2gs_LIBRARIES:%=-l%)
